name: bluealert
description: "Flood Alert application"
publish_to: 'none'

version: 1.0.0+1

# --- FIX 1: Updated SDK constraint to match modern Flutter versions ---
# Your Flutter version (3.29.3) uses a newer Dart SDK than 3.7.2.
# This range is safer and more compatible.
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- FIX 2: Updated several packages to their modern, stable versions ---
  # Using up-to-date packages is crucial for compatibility and security.
  http: ^1.2.1                   # Updated from 0.13.6
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  provider: ^6.1.2
  http_parser: ^4.0.2
  google_maps_flutter: ^2.6.1
  google_places_flutter: ^2.1.0
  geolocator: ^12.0.0
  exif: ^3.2.0
  connectivity_plus: ^6.0.3

  # --- FIX 3: This is the main fix for your build error ---
  workmanager: ^0.6.0             # Updated from 0.5.2

  path_provider: ^2.1.3
  path: ^1.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.0

  # --- FIX 4: Updated lints package to a more recent version ---
  flutter_lints: ^4.0.0           # Updated from 5.0.0 to a more standard version

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/default_avatar.png

#splash screen
flutter_native_splash:
  color: "#FFFFFF"
  # background_image: "assets/images/background.png" # Make sure this file exists or remove this line
  image: "assets/images/foreground.png"

  android_12:
    image: "assets/images/foreground.png"
    color: "#FFFFFF"

  android: true
  ios: true