name: bluealert
description: "Flood Alert application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  provider: ^6.1.2
  http_parser: ^4.0.2
  google_maps_flutter: ^2.6.1
  geolocator: ^14.0.2
  exif: ^3.2.0
  connectivity_plus: ^7.0.0
  video_player: ^2.8.6 
  permission_handler: ^12.0.1
  workmanager: ^0.8.0 
  chewie: ^1.7.5
  path_provider: ^2.1.3
  path: ^1.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/default_avatar.png

#splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/foreground.png"

  android_12:
    image: "assets/images/foreground.png"
    color: "#FFFFFF"

  android: true
  ios: true
